### ISSUE TITLE
Multiple About windows

### ISSUE THREAD

**Issue by rbtylee** [JeffHoogland/ePad#18]
One can click on the About button multiple times and open multiple about windows. Most apps such as Leafpad for example don't open multiple about windows in this case. This isn't so much a bug as it is a design choice, or in our case a lack of choice. We simply didn't consider it.

**Comment by JeffHoogland** [comment]
Should we handle this per-application or in the elm extensions about window tool?

**Comment by rbtylee** [comment]
I was wondering the same thing. I actually noticed this in epack and have a fix for it there. Looked at epad and fixed it locally in epad code. But the fix could certainly be moved to elm extensions. Can you envision any app needing more than one instance of an about window? My fix was to make the about window a simple singleton class, despite the advice some give not to use singleton classes. If I moved it to elm extensions, should I continue to implement it as a singleton? The single instance fix is nice and easy btw. So I lean that direction ...

**Comment by JeffHoogland** [comment]
I can't think of a relevant use case for needing it open twice.

**Comment by rbtylee** [comment]
I will move the fix to elm extensions sometime today and close this issue. Thanks for your feedback :+1:

**Comment by rbtylee** [comment]
Commit 8565190 here and my[ latest on py-elm extensions ](https://github.com/JeffHoogland/python-elm-extensions/commit/9895a304100060fc7df925fadf48aa23693ef62c) addresses this issue.
