### ISSUE TITLE
About still reports 0.9.5

### ISSUE THREAD

**Issue by NuLogicSystems** [JeffHoogland/ePad#19]
This is a minor issue, but you forgot to update the version string before creating the 0.9.6 tag for release.
`__version__ = "0.9.5"`
https://github.com/JeffHoogland/ePad/blob/master/epad
http://www.enlightenment.org/ss/e-5b819d09134ce7.99648827.jpg

**Comment by rbtylee** [comment]
Commit 73a1fef  addresses this.
