### ISSUE TITLE
ibus-m17n not working on ePad

### ISSUE THREAD

**Issue by drdhaval2785** [JeffHoogland/ePad#21]
When I try to type in Indian languages by ibus-m17n package,
ePad does not type in the Indian language.
It types in English language.

Gedit, atom, brackets etc work with ibus-m17n package well.

**Comment by rbtylee** [comment]
Sorry to take so long getting to this. I help sometimes with epad but it is really not my program nor do I even use it. I had hoped someone with more familiarity with localization issues would address this issue as I am a typical American and speak and use only english. But anyway ...

This is a support question and not an epad issue. I have zero familiarity with trying to type in 'Indian language' (which Indian lang?) in any application yet after a little googling and experimentation I was able to get epad to use the ibus-m17n package and [type in presumably Hindi](https://imgur.com/HAxPMZ9).

I would suggest asking in a [forum](https://www.linuxquestions.org/questions/bodhi-92/) with considerably more detail than you have provided here. What packages have you installed? What have you tried to do to make this work or make it work in gedit? What version of Bodhi are you using and what version of epad?

ePad relies upon the Enlightenment Foundation Libraries and whatever localization support it has is provided by these libraries and whatever the OS and window manager provides. I find no reason to suspect this is an ePad issue, or an EFL or Moksha Bug so I am closing this Issue.

**Comment by rbtylee** [comment]
[type in presumably Hindi](url)
